Todo network of data resource types:

@startuml

class home as "Home/Root of the API" <<H, #00FF00) >>
home : version
home --|> tenant : tenants


class tenant as "tenant"  <<O, #00FF00) >>
tenant : name
tenant --|> user : users
tenant --|> todo : todos


class todo as "todo"   <<I, #0000FF) >>
todo : many
todo --|> person : persons
todo --|> comment : comments
todo --|> file : files


class person as "Person"  <<P, #FF0000) >>
person : many
person --|> todo : todos
person --|> personImage : images
person --|> personComment : comments


class personImage as "Image"  <<P, #FF0000) >>
personImage : todo

class personComment as "Comment"  <<P, #FF0000) >>
personComment : todo


/'
 ' Integration Support
 ' =================== 
 '/

class user as "User"  <<A, #00FFFF) >>
user : name
note top
  A user encapsulates the concept of identity in the system 
end note

user --|> tenant : tenant
user --|> group : groups
user --|> todo : todos

class group as "Group"  <<A, #00FFFF) >>
group --|> role : roles

class role as "Role"  <<A, #00FFFF) >>


comment : many
file : todo

'
' Enumeration resources
' =====================
'

class todoStage  as "Todo States (enum)" <<E, #FF7700) >>
todoStage : name
todoStage : description

class todoType  as "Todo types (enum)" <<E, #FF7700) >>
todoStage : name
todoStage : description


@enduml