import Vue from 'vue';

/**
 * Find the element in the html (generated by linkify) based on its link relation and return the element
 * that contains the 'href' uri.
 *
 * TODO: opps, scope the HTMLElement rather than on document
 * TODO: there are bugs in this. It needs to be scoped to links and not items
 * TODO: [check: fixed] rel probably needs to be better scoped by regex too - there are false matches (eg search)
 *
 * @example
 *
 *  rel: create-form
 *
 *  <pre data-v-4a356f1e="">{
 *    <span class="key">"links":</span> [
 *        {
 *            <span class="key">"rel":</span> <span class="string">"create-form"</span>,
 *            <span class="key">"href":</span> <span class="string">"<a href="https://api.example.com/todo/form/create" class="linkified">https://api.example.com/todo/form/create</a>"</span>
 *        }
 *    ],
 *  </pre>
 *
 * @example
 *
 *  rel: edit-form (with patch)
 *
 *  <pre data-v-4a356f1e="">{
 *    <span class="key">"links":</span> [
 *        {
 *            <span class="key">"rel":</span> <span class="string">"edit-form"</span>,
 *            <span class="key">"href":</span> <span class="string">"<a href="https://api.example.com/todo/json-patch/create" class="linkified">https://api.example.com/todo/json-patch/create</a>"</span>
 *            <span class="key">"type":</span> <span class="string">"application/json-patch+json"</span>
 *        }
 *    ],
 *  </pre>
 * @param {string|RegExp} rel
 * @param {string} type media type
 * @param {Element} el - parent scope to search
 * @returns {Element[]}
 */
const findLinkRel = (rel, type, el = document) => {

    // look for all elements of space and class string (these have the link rels)
    // <span class="string">"create-form"</span>,
    return [...el.querySelectorAll('span.string')]
    // make sure it is a 'rel' sibling (ie in the links section)
    // ie <span class="key">"rel":</span>
        .filter(div => div.previousElementSibling && div.previousElementSibling.innerHTML.includes('rel'))
        // look for the text inside for the value of the link rel
        // eg <span class="string">"create-form"</span>,
        .filter(div => {
            if (typeof rel === 'string') {
                return div.innerText.includes(rel);
            } else if (rel instanceof RegExp) {
                return rel.test(div.innerText);
            }
        })
        // filter on type (or absence of type)
        //   <span class="string">"application/json-patch+json"</span>
        .filter(div => (type == null)
            // no type needs to ensure that there is also no type on the screen as well
            ? findElWithTypeKey(div) == null || !findElWithTypeKey(div).innerHTML.includes('type')
            // if there is a type, match against the given one
            : findElWithMediaType(div).innerHTML.includes(type)
        )
        // move forward two spans to find the Uri
        // <span class="string"><a href="https://api.example.com/todo/form/create" class="linkified">https://api.exa
        .map(div => findElWithHrefUri(div));
};

/**
 * Relative to the rel value (eg edit-form), find element of the type key element. Used to see
 * if the type is specified.
 *
 *    <span class="key">"rel":</span> <span class="string">"edit-form"</span>,  <-- start here
 *    <span class="key">"href":</span> <span class="string">"<a href="https://api.example.com/todo/json-patch/create" class="linkified">https://api.example.com/todo/json-patch/create</a>"</span>
 *    <span class="key">"type":</span> <span class="string">"application/json-patch+json"</span>
 *
 * @param {Element} el
 * @returns {Element | null}
 */
const findElWithTypeKey = el => el.nextElementSibling.nextElementSibling.nextElementSibling;

/**
 * Relative to the rel value (eg edit-form), find element of the media value element. Used to match
 * on the specified type.
 *
 *    <span class="key">"rel":</span> <span class="string">"edit-form"</span>,  <-- start here
 *    <span class="key">"href":</span> <span class="string">"<a href="https://api.example.com/todo/json-patch/create" class="linkified">https://api.example.com/todo/json-patch/create</a>"</span>
 *    <span class="key">"type":</span> <span class="string">"application/json-patch+json"</span>
 *
 *
 * @param {Element} el
 * @returns {Element | null}
 */
const findElWithMediaType = el => el.nextElementSibling.nextElementSibling.nextElementSibling.nextElementSibling;

/**
 * Relative to the rel value (eg edit-form), find element of the href-key value element.
 *
 *    <span class="key">"rel":</span> <span class="string">"edit-form"</span>,  <-- start here
 *    <span class="key">"href":</span> <span class="string">"<a href="https://api.example.com/todo/json-patch/create" class="linkified">https://api.example.com/todo/json-patch/create</a>"</span>
 *    <span class="key">"type":</span> <span class="string">"application/json-patch+json"</span>
 *
 *
 * @param {Element} el
 * @returns {Element | null}
 */
const findElWithHrefUri = el => el.nextElementSibling.nextElementSibling;

/**
 * Mount a new button onto the linkify html. The button will be added before the first child.
 *
 * @remarks
 *
 * In this case, it adds the button before the '"' (quotation marks) that delineate the uri
 *
 * @example
 *
 *      <button type="button" class="btn btn-secondary btn-sm">Add</button>
 *       "
 *       <a href="https://api.example.com/todo/form/create" class="linkified">https://api.example.com/todo/form/create</a>
 *       "
 * @param {Element} el span element that contains the <a> anchor of the href
 * @param {{?title:string, ?rel:string, ?type:string, ?onClick:Function}} propsData Vue properties of the component
 */
const addButtonToHref = (el, propsData = {}) => {

    // Instructions on how to dynamically add a component to the DOM
    // https://stackoverflow.com/questions/35927664/how-to-add-dynamic-components-partials-in-vue-js
    // https://css-tricks.com/creating-vue-js-component-instances-programmatically/
    const Btn = Vue.extend({
        template: '<b-button size="sm" variant="secondary" @click="onClick(rel,type)">{{title}}</b-button>',
        props: {
            title: {default: 'Edit'},
            onClick: {
                type: Function,
                default: () => {
                }
            },
            rel: {default: 'edit-form'},
            type: {default: null}
        }
    });

    const instance = new Btn({propsData});

    el && el.insertBefore(instance.$mount().$el, el.firstChild);
};

/**
 *  Add an action button on the linkify link relations html structure
 *
 * @param {string|RegExp} rel link relation to add button onto (eg self, create-form, edit-form)
 * @param {?string} type media type
 * @param {{title:string, onClick:function(rel)}} propsData Vue properties of the component
 */
const makeButtonOnLinkifyLinkRels = (rel, type, propsData) => {
    // parameters if type wasn't specified
    if (propsData == null) {
        propsData = type;
        type = null;
    }
    return findLinkRel(rel, type).forEach(el => addButtonToHref(el, {rel, type, ...propsData}));
};

export {makeButtonOnLinkifyLinkRels};